version: "3.6"
services:
  sfl-core-condition:
    image: actionmediamtl/sfl-core-condition:release-$RELEASE

# [DEPLOY & Re-Deploy]
# RELEASE=0.0.14 docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-deps --build

