version: "3.6"
services:
  core-condition:
    image: actionmediamtl/sfl-core-condition:release-0.0.13
    container_name: core-condition 
    expose:
      - "8084"
    environment:
      - VIRTUAL_HOST=core-condition.test
    volumes:
      - .:/var/www/core
    tty: true  
  sfl-api-advertiser:
    image: actionmediamtl/sfl-api-advertiser:release-0.0.2
    container_name: sfl-api-advertiser 
    expose:
      - "8085"
    environment:
      - VIRTUAL_HOST=sfl-api-advertiser.test
    volumes:
      - .:/var/www/api-adv
    tty: true  
  sfl-api-publisher:
    image: actionmediamtl/sfl-api-publisher:release-0.0.2
    container_name: sfl-api-publisher 
    expose:
      - "8086"
    environment:
      - VIRTUAL_HOST=sfl-api-publisher.test
    volumes:
      - .:/var/www/api-pub
    tty: true  
  sfl-platform-advertiser:
    image: actionmediamtl/sfl-platform-advertiser:release-0.0.4
    container_name: sfl-platform-advertiser 
    expose:
      - "8087"
    environment:
      - VIRTUAL_HOST=sfl-platform-advertiser.test
    volumes:
      - .:/var/www/plat-adv
    tty: true  
  sfl-platform-publisher:
    image: actionmediamtl/sfl-platform-publisher:release-0.0.2
    container_name: sfl-platform-publisher 
    expose:
      - "8088"
    environment:
      - VIRTUAL_HOST=sfl-platform-publisher.test
    volumes:
      - .:/var/www/plat-pub
    tty: true  
  
networks:
  default:
    external:
      name: sfl-network